@baseUrl = http://localhost:3333
@authToken = {{authentication.response.body.access_token}}
@dateNow = {{$datetime iso8601}}


# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "fred",
  "email": "fred6@fred.com",
  "password": "123456",
  "role": "TEACHER"
}

###

# @name get_users
GET {{baseUrl}}/accounts
Content-Type: application/json

###

# @name authentication
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "fred6@fred.com",
  "password": "123456"
}

###

# @name create_appointment
POST {{baseUrl}}/appointments
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "spotId": "3bb31a6b-a7ef-408b-9378-b811f8a5f47f", 
  "subject":"programing", 
  "duration": "120"
}

###

# @name create_spot
POST {{baseUrl}}/spots
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "date": "2024-11-26T01:03:39.450Z"
}

###

# @name cancel_appointment
PATCH  {{baseUrl}}/cancel-appointment/08e59bef-c156-479e-bbd1-eba5a043a6dd
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name delete_spot
DELETE   {{baseUrl}}/spots/72bbf6a7-3151-4550-a0b9-799da1e8c97c
Content-Type: application/json
Authorization: Bearer {{authToken}}
